Repository Donggrina/Frontend, pull requests merged in 2024-06, with the labels that each got.

#37 Refactor: input, label 컴포넌트 분리
  components/common/Input/index.tsx
  components/common/Label/index.tsx
  pages/input-test/index.module.scss
  pages/input-test/index.tsx
Labels: Refactoring

#42 Fix: 파일명 수정
  pages/_app.tsx
Labels: bug

#38 Feat: 로그인 기능 추가 및 환경변수 설정
  components/common/common-button/common-button.module.scss
  components/login/google-button/google-button.module.scss
  components/login/google-button/google-button.tsx
  components/login/kakao-button/kakao-button.module.scss
  components/login/kakao-button/kakao-button.tsx
  components/start-family/link-list/link-list.module.scss
  config/index.ts
Labels: Feature

#40 Feat: 로그인 시 토큰 저장 및 middleware 설정
  components/start-family/introduce-text/introduce-text.module.scss
  middleware.ts
  pages/start-family/index.tsx
Labels: Feature

#45 Fix: 폰트 추가 및 start-family페이지 폰트 변경
  components/start-family/introduce-text/introduce-text.module.scss
  public/fonts/LaundryGothic_subset_Bold.woff2
  public/fonts/LaundryGothic_subset_Regular.woff2
  styles/globals.css
Labels: UI, Refactoring

#43 Feat: nav 컴포넌트 작업 및 middleware 수정
  components/common/nav/gooey/gooey.tsx
  components/common/nav/nav-list/nav-list-item.module.scss
  components/common/nav/nav-list/nav-list-item.tsx
  components/common/nav/nav.module.scss
  components/common/nav/nav.tsx
  components/common/nav/types/nav.ts
  pages/_app.tsx
  pages/family/index.tsx
  public/images/nav/book.svg
  public/images/nav/calendar.svg
  public/images/nav/home.svg
  public/images/nav/smile.svg
  public/images/nav/user.svg
  styles/globals.css
  utils/IsNav.ts
  utils/constants/navData.ts
  utils/is-nav.ts
Labels: Feature, UI, Apply code review

#46 Fix: 헤더 유무 판단 유틸함수 파일명 변경
  pages/_app.tsx
  utils/is-header.ts
Labels: Apply code review

#56 Feat: 공통 radio 컴포넌트 개발
  components/common/radio/context/radio-context.tsx
  components/common/radio/radio-input/radio-input.tsx
  components/common/radio/radio-label/radio-label.tsx
  components/common/radio/radio.module.scss
  components/common/radio/radio.tsx
  pages/test/radio-test/index.tsx
  styles/globals.css
Labels: Feature, UI, Apply code review

#60 Feat: api 데이터 타입 지정
  types/diary/details.ts
  types/diary/index.ts
  types/diary/search.ts
  types/growth/details.ts
  types/growth/index.ts
  types/growth/search.ts
  types/my-page/family/index.ts
  types/my-page/pet/detsils.ts
  types/my-page/pet/index.ts
  types/my-page/user/index.ts
  types/schedule/details.ts
  types/schedule/index.ts
  types/story/details.ts
  types/story/index.ts
Labels: Feature

#62 Rename: css 분할 작업
  styles/color.css
  styles/font.css
  styles/globals.css
Labels: Feature, question, Apply code review

#57 Feat: 공통 button 컴포넌트 개발
  components/common/button/button.module.scss
  components/common/button/button.tsx
  components/common/button/hyperlink.tsx
  components/common/button/types/button-type.ts
  components/common/common-button/common-button.module.scss
  components/common/nav/nav-list/nav-list-item.module.scss
  components/login/google-button/google-button.module.scss
  components/login/kakao-button/kakao-button.module.scss
  components/start-family/link-list/link-item.tsx
  components/start-family/link-list/link-list.module.scss
  components/start-family/link-list/link-list.tsx
  components/start-family/link-list/types/link-type.ts
  lib/constants/calendar-constants.ts
  pages/test/button-test/index.module.scss
  pages/test/button-test/index.tsx
  pages/test/input-test/index.module.scss
  pages/test/input-test/index.tsx
Labels: Feature, UI, Apply code review

#47 Design: 일정페이지 달력, 할일 컴포넌트 제작
  components/calendar/calendar-container.module.scss
  components/calendar/calendar-container.tsx
  components/calendar/calendar-todo.module.scss
  components/calendar/calendar-todo.tsx
  components/calendar/cat-checkbox.tsx
  components/calendar/create-todo-button.module.scss
  components/calendar/create-todo-button.tsx
  components/calendar/dog-checkbox.tsx
  lib/constants/calendar-constants.ts
  pages/calendar/calendar.module.scss
  pages/calendar/create/create.module.scss
  pages/calendar/create/index.tsx
  pages/calendar/index.tsx
  pages/test/modal-test/index.tsx
  public/images/calendar/cat-off.svg
  public/images/calendar/cat-on.svg
  public/images/calendar/dog-off.svg
  public/images/calendar/dog-on.svg
  public/images/calendar/new-todo.svg
  styles/color.css
  utils/constants/navData.ts
  utils/get-date-count.ts
  utils/get-day.ts
  utils/get-first-day.ts
  utils/get-seventh-date.ts
  utils/is-leap-year.ts
  utils/validate-date.ts
  utils/validate-month.ts
  utils/validate-year.ts
Labels: Feature, UI, Apply code review

#54 Feat: main input, date input, weight input 구현
  components/common/Form/Form.module.scss
  components/common/Form/index.tsx
  components/common/Input/Input.module.scss
  components/common/Input/date-input/date-input.module.scss
  components/common/Input/date-input/index.tsx
  components/common/Input/index.tsx
  components/common/Input/input-type.ts
  components/common/Input/main-input/index.tsx
  components/common/Input/main-input/main-input.module.scss
  components/common/Input/mixins.scss
  components/common/Input/weight-input/index.tsx
  components/common/Input/weight-input/weight-input.module.scss
  pages/test/input-test/index.tsx
  utils/validations/validate-date.ts
Labels: Feature, UI, Apply code review

#59 Feat: 캘린더 컴파운드 패턴 적용 및 리팩토링
  components/calendar-compound/calendar.tsx
  components/calendar-compound/calendar.type.ts
  components/calendar-compound/components/index.ts
  components/calendar-compound/components/month/calendar-month.module.scss
  components/calendar-compound/components/month/calendar-month.tsx
  components/calendar-compound/components/weekly/calendar-weekly.module.scss
  components/calendar-compound/components/weekly/calendar-weekly.tsx
  components/calendar-compound/components/year/calendar-year.module.scss
  components/calendar-compound/components/year/calendar-year.tsx
  hooks/use-select.tsx
  package-lock.json
  package.json
  pages/test/calendar/index.tsx
  utils/date/date.constant.ts
  utils/date/date.core.ts
  utils/date/date.type.ts
  utils/date/date.utils.ts
Labels: Feature, UI, Refactoring

#68 Feat: Select input 구현 완료
  components/common/Form/index.tsx
  components/common/Input/input-type.ts
  components/common/select/drop-down/drop-down.module.scss
  components/common/select/drop-down/index.tsx
  components/common/select/index.tsx
  components/common/select/select.module.scss
  hooks/use-close-dropdown.tsx
  package-lock.json
  package.json
  pages/test/input-test/index.tsx
  public/images/select/dropdown-down.svg
  public/images/select/dropdown-up.svg
Labels: Feature, UI

#66 Feat: 공용 모달 수정, 일정 추가 페이지 제작 중
  components/calendar/calendar-modal-calendar.module.scss
  components/calendar/calendar-modal-calendar.tsx
  components/calendar/calendar-modal-time-selector.module.scss
  components/calendar/calendar-modal-time-selector.tsx
  components/calendar/calendar-modal.module.scss
  components/calendar/calendar-modal.tsx
  components/calendar/time-scroller.module.scss
  components/calendar/time-scroller.tsx
  components/common/modal/modal-portal.tsx
  components/common/modal/modal.module.scss
  components/common/modal/modal.tsx
  hooks/use-modal.tsx
  lib/constants/calendar-constants.ts
  pages/calendar/create/create.module.scss
  pages/calendar/create/index.tsx
  pages/test/button-test/index.tsx
  pages/test/modal-test/index.tsx
  styles/color.css
  utils/get-calendar-array.ts
  utils/get-time-scroll-position.ts
Labels: Feature, UI, Refactoring

#72 Refactor: radio 컴포넌트 리팩토링
  components/common/radio/context/radio-context.tsx
  components/common/radio/radio-input/radio-input.tsx
  components/common/radio/radio-label/radio-label.tsx
  components/common/radio/radio.tsx
  pages/test/radio-test/index.tsx
Labels: Refactoring

#75 Feat: 로그인 시 refreshToken 쿠키에 저장
  middleware.ts
  pages/start-family/index.tsx
  styles/globals.css
Labels: Feature

#76 Refactor: 라벨 컴포넌트 컴파운드 패턴 활용해 분리
  components/common/Form/index.tsx
  components/common/Input/date-input/index.tsx
  components/common/Input/input-type.ts
  components/common/Input/main-input/index.tsx
  components/common/Input/weight-input/index.tsx
  components/common/select/index.tsx
  pages/test/input-test/index.tsx
Labels: Refactoring

#77 Feat: 연도 기능 추가
  components/calendar-compound/calendar.tsx
  components/calendar-compound/calendar.type.ts
  components/calendar-compound/components/weekly/calendar-weekly.tsx
  components/calendar-compound/components/year/calendar-year.module.scss
  components/calendar-compound/components/year/calendar-year.tsx
  utils/date/date.utils.ts
Labels: Feature

#80 Feat: 성장 기록 list item 컴포넌트 구현
  components/growth/list/index.tsx
  components/growth/list/list-footer/index.tsx
  components/growth/list/list-footer/list-footer.module.scss
  components/growth/list/list-header/index.tsx
  components/growth/list/list-header/list-header.module.scss
  components/growth/list/list.module.scss
  components/growth/profile/index.tsx
  components/growth/profile/profile.module.scss
  pages/growth/index.tsx
  public/images/growth/categroy-icon.svg
  public/images/growth/chat-icon.svg
  public/images/growth/empty-heart.svg
  public/images/growth/fill-heart.svg
  public/images/growth/profile-icon.svg
Labels: UI

#84 Feat: 공용 추가 버튼 제작
  components/calendar-monthly/calendar-container.module.scss
  components/calendar-monthly/calendar-container.tsx
  components/calendar-monthly/calendar-modal-calendar.module.scss
  components/calendar-monthly/calendar-modal-calendar.tsx
  components/calendar-monthly/calendar-modal-time-selector.module.scss
  components/calendar-monthly/calendar-modal-time-selector.tsx
  components/calendar-monthly/calendar-modal.module.scss
  components/calendar-monthly/calendar-modal.tsx
  components/calendar-monthly/calendar-todo-date.module.scss
  components/calendar-monthly/calendar-todo-date.tsx
  components/calendar-monthly/calendar-todo.module.scss
  components/calendar-monthly/calendar-todo.tsx
  components/calendar-monthly/create-todo-button.module.scss
  components/calendar-monthly/create-todo-button.tsx
  components/calendar-monthly/pet-radio.module.scss
  components/calendar-monthly/pet-radio.tsx
  components/calendar-monthly/time-scroller.module.scss
  components/calendar-monthly/time-scroller.tsx
  components/calendar/cat-checkbox.tsx
  components/calendar/create-todo-button.tsx
  components/calendar/dog-checkbox.tsx
  components/common/add-button/add-button.module.scss
  components/common/add-button/add-button.tsx
  lib/constants/calendar-constants.ts
  pages/calendar/calendar.module.scss
  pages/calendar/create/create.module.scss
  pages/calendar/create/index.tsx
  pages/calendar/index.tsx
  public/images/calendar/check.svg
  public/images/calendar/new-todo.svg
  styles/color.css
Labels: Feature, UI

#83 Feat: 다이어리 페이지 card 컴포넌트 구현
  components/diaries/diary-content/content-image/content-image.module.scss
  components/diaries/diary-content/content-image/index.tsx
  components/diaries/diary-content/content/content.module.scss
  components/diaries/diary-content/content/index.tsx
  components/diaries/diary-content/diary-content.module.scss
  components/diaries/diary-content/diary-content.tsx
  components/diaries/diary-content/profile/index.tsx
  components/diaries/diary-content/profile/profile.module.scss
  components/diaries/diary-content/response/index.tsx
  components/diaries/diary-content/response/response.module.scss
  components/diaries/mock-data.ts
  pages/_app.tsx
  pages/diaries/index.tsx
  public/images/diaries/content-image.svg
  public/images/diaries/heart-click.svg
  public/images/diaries/heart.svg
  public/images/diaries/message.svg
  public/images/diaries/more-horizontal.svg
  public/images/diaries/plus-circle.svg
  public/images/diaries/profile.svg
  public/images/diaries/vector.svg
Labels: Feature, UI

#88 Refactor: css 수정 및 폰트 수정
  components/common/Header/Header.module.scss
  components/common/nav/gooey/gooey.tsx
  components/common/nav/nav.module.scss
  pages/_document.tsx
  public/fonts/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-Medium.subset.woff2
  styles/font.css
  styles/globals.css
Labels: UI, Refactoring

#89 FIx: date input과 select input 버그 해결
  components/common/Input/date-input/index.tsx
  components/common/Input/input-type.ts
  components/common/select/drop-down/index.tsx
  components/common/select/index.tsx
  hooks/use-close-dropdown.tsx
  pages/test/input-test/index.tsx
  utils/validations/date-validation.ts
  utils/validations/validate-date.ts
Labels: bug, Feature, Refactoring

#91 Fix: 팝오버 위치 오류
  components/kebab/kebab.module.scss
  components/kebab/kebab.tsx
  hooks/use-toggle.ts
Labels: bug

#93 Feat: 반려동물 추가 페이지 작업 완료
  api/image-api/index.ts
  api/index.ts
  api/my/groups/index.ts
  api/my/pets/index.ts
  components/common/nav/nav.tsx
  components/common/radio/context/radio-context.tsx
  components/common/radio/radio.module.scss
  components/common/radio/radio.tsx
  components/common/select/index.tsx
  components/common/select/select.module.scss
  components/start-pet/entry-form/entry-form.module.scss
  components/start-pet/entry-form/entry-form.tsx
  components/start-pet/file-image/file-image.module.scss
  components/start-pet/file-image/file-image.tsx
  components/start-pet/file-input/file-input.module.scss
  components/start-pet/file-input/file-input.tsx
  middleware.ts
  pages/start-family/entry-info/index.tsx
  pages/start-pet/index.module.scss
  pages/start-pet/index.tsx
  public/images/start-pet/Dog.png
  public/images/start-pet/fileButton.svg
  utils/constants/entry-data.ts
  utils/constants/nav-data.ts
  utils/is-nav.ts
Labels: Feature, UI

#96 Fix: 연도를 바꾸면 일수와 요일이 안바뀌는 문제 수정
  components/calendar-compound/components/weekly/calendar-weekly.tsx
  utils/date/date.utils.ts
Labels: bug, Feature

#100 Feat: 반려동물 선택 radio 구현
  api/calendar/request.type.ts
  components/calendar-monthly/pet-radio.module.scss
  components/calendar-monthly/pet-radio.tsx
  next.config.mjs
  pages/calendar/create/create.module.scss
  pages/calendar/create/index.tsx
  public/images/calendar/check-circle.svg
  styles/color.css
Labels: Feature, UI

#99 Chore: 빌드 오류 주석 처리 pr
  api/growth/index.ts
  components/calendar-monthly/calendar-modal-time-selector.tsx
  components/common/Input/date-input/index.tsx
  components/growth/list/index.tsx
  components/growth/list/list-footer/index.tsx
  components/growth/list/list-footer/list-footer.module.scss
  components/growth/list/list-header/index.tsx
  components/growth/list/list.module.scss
  hooks/queries/growth/useGetGrowthQueries.ts
  hooks/queries/growth/usePostGrowthQuery.ts
  package-lock.json
  pages/calendar/create/index.tsx
  pages/growth/create/create.module.scss
  pages/growth/create/index.tsx
  pages/growth/growth.module.scss
  pages/growth/index.tsx
  public/images/growth/chat-icon.svg
  public/images/growth/empty-heart.svg
  public/images/growth/fill-heart.svg
  styles/globals.css
  types/date.ts
  types/growth/details.ts
  types/growth/index.ts
  utils/constants/calendar-constants.ts
  utils/convert-local-date.ts
  utils/get-calendar-array.ts
  utils/get-day.ts
  utils/get-time-scroll-position.ts
Labels: bug

#101 Feat: 다이어리, 성장, 일정 기록 없을 때 UI 추가
  components/family/diary/family-diary-contents-empty.module.scss
  components/family/diary/family-diary-contents-empty.tsx
  components/family/diary/family-diary-contents.module.scss
  components/family/diary/family-diary-contents.tsx
  components/family/diary/family-diary.tsx
  components/family/diary/layout/family-diary-layout.module.scss
  components/family/diary/layout/family-diary-layout.tsx
  components/family/growth/family-growth-empty.module.scss
  components/family/growth/family-growth-empty.tsx
  components/family/growth/family-growth.tsx
  components/family/schedule/family-schedule-empty.module.scss
  components/family/schedule/family-schedule-empty.tsx
  components/family/schedule/family-schedule.tsx
  public/images/family/add-black-icon.svg
  public/images/family/alert-triangle.svg
Labels: UI

#103 Feat: Kebab 컴포넌트 모달 관련 수정.
  components/kebab/kebab.tsx
  components/kebab/kebab.type.ts
  hooks/use-outside.ts
  pages/test/kebab/index.tsx
  utils/index.ts
Labels: Feature

#106 Feat: 패밀리 데이터 연동.
  .vscode/settings.json
  components/family/diary/empty/family-diary-empty.module.scss
  components/family/diary/empty/family-diary-empty.tsx
  components/family/diary/family-diary-contents.tsx
  components/family/diary/family-diary.tsx
  components/family/diary/item/family-diary-item.module.scss
  components/family/diary/item/family-diary-item.tsx
  components/family/growth/empty/family-growth-empty.module.scss
  components/family/growth/empty/family-growth-empty.tsx
  components/family/growth/family-growth-contents.tsx
  components/family/growth/family-growth.module.scss
  components/family/growth/family-growth.tsx
  components/family/growth/item/family-growth-item.module.scss
  components/family/growth/item/family-growth-item.tsx
  components/family/growth/list/family-growth-list.module.scss
  components/family/growth/list/family-growth-list.tsx
  components/family/schedule/empty/family-schedule-empty.module.scss
  components/family/schedule/empty/family-schedule-empty.tsx
  components/family/schedule/family-schedule-contents.tsx
  components/family/schedule/family-schedule.module.scss
  components/family/schedule/family-schedule.tsx
  components/family/schedule/item/family-schedule-item.module.scss
  components/family/schedule/item/family-schedule-item.tsx
  components/family/schedule/list/family-schedule-list.module.scss
  components/family/schedule/list/family-schedule-list.tsx
  components/suspensive/suspensive.tsx
  hooks/queries/family/index.ts
Labels: Feature, Refactoring

#110 Fix: 공통 버튼 스타일 수정 및 nav 수정
  components/common/button/button.module.scss
  public/images/nav/growth.svg
  public/images/nav/user.svg
  utils/constants/nav-data.ts
Labels: bug, UI

#114 Feat: RT 기능 구현
  api/auth/index.ts
  api/index.ts
  pages/test/refresh-test/index.tsx
Labels: Feature

#119 Fix: Rt 인터셉터 수정
  api/index.ts
Labels: bug

#120 Feat: 성장기록 메인화면, 추가화면 구현 완료
  .vscode/settings.json
  api/growth/index.ts
  components/calendar-monthly/pet-radio.tsx
  components/growth/list/index.tsx
  components/growth/list/list-header/index.tsx
  components/growth/list/list.module.scss
  components/growth/profile/index.tsx
  components/growth/profile/profile.module.scss
  hooks/queries/growth/use-get-growth-queries.ts
  hooks/queries/growth/use-post-growt-query.ts
  hooks/queries/growth/usePostGrowthQuery.ts
  pages/growth/create/category-inputs/category-inputs.module.scss
  pages/growth/create/category-inputs/index.tsx
  pages/growth/create/complete-modal/complete-modal.module.scss
  pages/growth/create/complete-modal/index.tsx
  pages/growth/create/create.module.scss
  pages/growth/create/index.tsx
  pages/growth/index.tsx
  public/images/growth/selected-category.svg
  public/images/growth/unselected-category.svg
  types/growth/details.ts
  types/growth/index.ts
  utils/constants/growth.ts
Labels: Feature, UI

#123 Fix: 일정 등록 시계 스크롤 속도 수정
  components/calendar-monthly/time-scroller.tsx
Labels: bug, Refactoring

#116 Feat: 일정페이지 완료된거 패밀리에 적용. (다른분들 작업 대기중이에요. 이건 머지 하지말아주세요)
  .vscode/settings.json
  components/calendar-compound/components/weekly/calendar-weekly.tsx
  components/family/diary/family-diary-contents.tsx
  components/family/diary/family-diary.tsx
  components/family/growth/family-growth-contents.tsx
  components/family/growth/family-growth.tsx
  components/family/schedule/empty/family-schedule-empty.tsx
  components/family/schedule/family-schedule-contents.tsx
  components/family/schedule/family-schedule.tsx
  components/family/schedule/item/family-schedule-item.module.scss
  components/family/schedule/item/family-schedule-item.tsx
  components/family/schedule/list/family-schedule-list.tsx
  hooks/queries/family/index.ts
  utils/date/date.utils.ts
Labels: Feature

#128 Feat: 마이페이지 가족관리 페이지 구현
  api/index.ts
  api/my/groups/index.ts
  components/common/share/share.tsx
  components/mypage/family/add-family/add-family.module.scss
  components/mypage/family/add-family/add-family.tsx
  components/mypage/family/family-list-item/delete-member-modal/delete-member-modal.module.scss
  components/mypage/family/family-list-item/delete-member-modal/delete-member-modal.tsx
  components/mypage/family/family-list-item/family-list-item.module.scss
  components/mypage/family/family-list-item/family-list-item.tsx
  components/mypage/family/family-list/family-list.tsx
  components/mypage/family/family-util-buttons/family-add-button/family-add-button.tsx
  components/mypage/family/family-util-buttons/family-delete-button/delete-modal/delete-modal.module.scss
  components/mypage/family/family-util-buttons/family-delete-button/delete-modal/delete-modal.tsx
  components/mypage/family/family-util-buttons/family-delete-button/family-delete-button.tsx
  components/mypage/family/family-util-buttons/family-rename-button/family-rename-button.tsx
  components/mypage/family/family-util-buttons/family-rename-button/rename-modal/rename-modal.module.scss
  components/mypage/family/family-util-buttons/family-rename-button/rename-modal/rename-modal.tsx
  components/mypage/family/family-util-buttons/family-util-buttons.module.scss
  components/mypage/family/family-util-buttons/family-util-buttons.tsx
  components/start-pet/finish/pets-link-list/pets-link-list.tsx
  hooks/queries/my/family/useGetFamilyQueries.ts
  hooks/queries/my/family/usePostFamilyQueries.ts
  pages/mypage/family/index.module.scss
  pages/mypage/family/index.tsx
  pages/mypage/index.tsx
  pages/start-family/entry-info/index.tsx
  pages/start-family/register-code/index.tsx
  public/images/mypage/minus-circle.svg
  public/images/mypage/owner.svg
  public/images/mypage/plus-circle.svg
  utils/is-nav.ts
Labels: Feature

#132 Feat: 헤더 아이콘 PNG -> SVG로 변경
  components/common/Header/index.tsx
  public/images/header/arrow-left-black.svg
  public/images/header/left-arrow.png
  public/images/header/logo.svg
  public/images/header/sub-logo.png
Labels: UI

#138 Refactor: 모달, 버튼 수정 및 구글 로그인 추가
  components/calendar-monthly/calendar-todo-post-success.tsx
  components/common/button/button.tsx
  components/common/modal/modal.module.scss
  components/mypage/family/family-list-item/delete-member-modal/delete-member-modal.tsx
  components/mypage/family/family-util-buttons/family-delete-button/delete-modal/delete-modal.tsx
  components/mypage/family/family-util-buttons/family-delete-button/family-delete-button.tsx
  components/mypage/family/family-util-buttons/family-rename-button/rename-modal/rename-modal.tsx
  components/start-pet/finish/share-modal/share-modal.tsx
  config/index.ts
  pages/growth/create/complete-modal/index.tsx
Labels: Refactoring

#134 Refactor: 이미지 업로드 로직 수정(모달 수정하고 머지하겠습니다)
  components/common/modal/modal.module.scss
  components/mypage/family/family-util-buttons/family-rename-button/rename-modal/rename-modal.tsx
  components/start-pet/file-image/file-image.tsx
  components/start-pet/file-input/file-input.tsx
  components/start-pet/image-modal/image-modal.module.scss
  components/start-pet/image-modal/image-modal.tsx
  pages/start-pet/[id]/index.tsx
  public/images/pets/plus-circle.svg
  types/my-page/pet/detsils.ts
Labels: Feature, Refactoring

#146 Feat: 스켈레톤 ui 폴더 구조 셋팅
  components/skeleton/calendar/test.tsx
  components/skeleton/diary/test.tsx
  components/skeleton/family/test.tsx
  components/skeleton/growth/test.tsx
  components/skeleton/image/test.tsx
  components/skeleton/mypage/test.tsx
  styles/color.css
Labels: documentation

#139 Feat: 반려동물 관리 페이지 구현
  components/common/add-pet-form/add-pet-form.tsx
  components/common/modify-pet-form/modify-pet-form.tsx
  components/mypage/pet/add-pet/add-pet.module.scss
  components/mypage/pet/add-pet/add-pet.tsx
  components/mypage/pet/pet-list-item/pet-list-item.module.scss
  components/mypage/pet/pet-list-item/pet-list-item.tsx
  components/mypage/pet/pet-list/pet-list.module.scss
  components/mypage/pet/pet-list/pet-list.tsx
  hooks/queries/my/pets/usePostPetsQueries.ts
  pages/mypage/pet/[id]/index.tsx
  pages/mypage/pet/add/index.tsx
  pages/mypage/pet/index.module.scss
  pages/mypage/pet/index.tsx
  pages/start-pet/[id]/index.tsx
  pages/start-pet/index.module.scss
  pages/start-pet/index.tsx
  public/images/mypage/chevron-left.svg
Labels: Feature

#142 Feat: 다이어리 상세 페이지 구현
  api/diaries/index.ts
  components/calendar-monthly/calendar-todo.module.scss
  components/calendar-monthly/calendar-todo.tsx
  components/diaries/diary-content/comment/diary-comment-edit.module.scss
  components/diaries/diary-content/comment/diary-comment-edit.tsx
  components/diaries/diary-content/comment/diary-comment-form.module.scss
  components/diaries/diary-content/comment/diary-comment-form.tsx
  components/diaries/diary-content/comment/diary-comment-reply.module.scss
  components/diaries/diary-content/comment/diary-comment-reply.tsx
  components/diaries/diary-content/comment/diary-comment.module.scss
  components/diaries/diary-content/comment/diary-comment.tsx
  hooks/queries/diary/use-child-comment-mutation.ts
  hooks/queries/diary/use-comment-post-mutation.ts
  hooks/queries/diary/use-comment-put-mutation.ts
  hooks/queries/diary/use-diary-mutation.ts
  hooks/queries/diary/use-diary-query.ts
  hooks/queries/diary/use-parent-comment-mutation.ts
  pages/calendar/[calendarId]/index.tsx
  pages/diaries/[diaryId]/diary-id.module.scss
  pages/diaries/[diaryId]/index.tsx
  public/images/diaries/post-comment-off.svg
  public/images/diaries/post-comment-on.svg
  utils/constants/nav-data.ts
  utils/disintegrate-date-time.ts
Labels: Feature, UI

#143 Feat: 성장기록 상세 화면 구현 완료
  components/growth/list/index.tsx
  components/growth/list/list-header/index.tsx
  pages/growth/[growthId]/content/content.module.scss
  pages/growth/[growthId]/content/index.tsx
  pages/growth/[growthId]/edit/index.tsx
  pages/growth/[growthId]/growth-detail.module.scss
  pages/growth/[growthId]/index.tsx
  pages/growth/create/category-inputs/index.tsx
  pages/growth/create/index.tsx
  public/images/category/abnormalSymptom-detail.svg
  public/images/category/food-detail.svg
  public/images/category/hospital-detail.svg
  public/images/category/snack-detail.svg
  public/images/growth/abnormalSymptom-memo.svg
  public/images/growth/food-memo.svg
  public/images/growth/hospital-memo.svg
  public/images/growth/snack-memo.svg
  styles/color.css
  types/growth/details.ts
  utils/constants/growth.ts
Labels: Feature, UI

#148 Feat: 성장기록 메인화면 카테고리 이미지 설정
  components/growth/content/content.module.scss
  components/growth/content/index.tsx
  components/growth/list/list-header/index.tsx
  components/growth/list/list-header/list-header.module.scss
  pages/growth/[growthId]/edit/index.tsx
  pages/growth/[growthId]/index.tsx
  pages/growth/create/create.module.scss
  pages/growth/create/index.tsx
  public/images/category/abnormalSymptom-icon.png
  public/images/category/food-icon.png
  public/images/category/hospital-icon.png
  public/images/category/snack-icon.png
  utils/constants/growth.ts
Labels: Feature, UI

#124 Feat: 마이페이지 만들기
  api/my/user/index.ts
  components/common/Input/main-input/index.tsx
  components/common/Input/main-input/main-input.module.scss
  components/mypage/profile/input/profile-input.module.scss
  components/mypage/profile/input/profile-input.tsx
  components/mypage/profile/modal/image-upload-modal.module.scss
  components/mypage/profile/modal/image-upload-modal.tsx
  components/mypage/profile/modal/nickname-modal.module.scss
  components/mypage/profile/modal/nickname-modal.tsx
  components/mypage/profile/my-page-profile.module.scss
  components/mypage/profile/my-page-profile.tsx
  components/mypage/profile/upload/image-upload.module.scss
  components/mypage/profile/upload/image-upload.tsx
  hooks/queries/my/user/mutation.ts
  hooks/queries/my/user/query.ts
  hooks/use-upload.ts
  types/my-page/user/index.ts
Labels: Feature, UI

#149 Fix: 일정 시간 설정 ui 수정
  components/calendar-monthly/time-scroller.module.scss
  components/calendar-monthly/time-scroller.tsx
Labels: bug, UI

#150 Feat: 다이어리 이미지 컴포넌트 구현
  components/diaries/diary-images/diary-images.module.scss
  components/diaries/diary-images/index.tsx
  pages/diaries/[diaryId]/index.tsx
Labels: Feature, UI

#154 Feat: 시계 스크롤러 클릭으로 선택 기능 추가
  api/calendar/request.ts
  api/calendar/request.type.ts
  api/search/index.ts
  api/search/index.type.ts
  components/calendar-monthly/calendar-todo.tsx
  components/calendar-monthly/time-scroller.tsx
  components/search/search-filter.tsx
  components/search/search-form.module.scss
  components/search/search-form.tsx
  components/search/search-pet-checkbox.tsx
  hooks/queries/search/use-results-query.ts
  pages/calendar/[calendarId]/index.tsx
  pages/calendar/search/index.tsx
  pages/calendar/search/search.module.scss
  pages/diaries/search/index.tsx
  pages/diaries/search/search.module.scss
  pages/family/search/index.tsx
  pages/family/search/search.module.scss
  pages/growth/search/index.tsx
  pages/growth/search/search.module.scss
  types/search/index.ts
  utils/constants/search.ts
Labels: Feature

#155 Feat: 스켈레톤 애니메이션 설정 및 pull to refresh 구현
  components/calendar-monthly/calendar-todos.tsx
  components/common/Header/Header.module.scss
  components/common/modify-pet-form/modify-pet-form.tsx
  components/mypage/family/family-list/family-list.tsx
  components/mypage/family/family-util-buttons/family-util-buttons.tsx
  components/mypage/pet/pet-list/pet-list.module.scss
  components/mypage/pet/pet-list/pet-list.tsx
  components/mypage/profile/my-page-profile.tsx
  components/skeleton/calendar/calendar-details-skeleton.module.scss
  components/skeleton/calendar/calendar-details-skeleton.tsx
  components/skeleton/calendar/calendar-list-skeleton.module.scss
  components/skeleton/calendar/calendar-list-skeleton.tsx
  components/skeleton/calendar/test.tsx
  components/skeleton/mypage/family/family-button-skeleton.tsx
  components/skeleton/mypage/family/family-skeleton.tsx
  components/skeleton/mypage/family/skeleton.module.scss
  components/skeleton/mypage/pet/pet-form-skeleton.module.scss
  components/skeleton/mypage/pet/pet-form-skeleton.tsx
  components/skeleton/mypage/pet/pet-image-skeleton.module.scss
  components/skeleton/mypage/pet/pet-image-skeleton.tsx
  components/skeleton/mypage/profile-skeleton.module.scss
  components/skeleton/mypage/profile-skeleton.tsx
  components/skeleton/mypage/test.tsx
  components/skeleton/skeleton-animation.module.scss
  components/spinner/spinner.module.scss
  components/spinner/spinner.tsx
  components/start-pet/finish/pets-list/pets-list.tsx
  hooks/use-pull-to-refresh.tsx
  pages/_app.tsx
  pages/calendar/create/index.tsx
  pages/mypage/family/index.tsx
  pages/mypage/index.tsx
  pages/mypage/pet/index.module.scss
  pages/mypage/pet/index.tsx
  styles/color.css
  types/my-page/family/index.ts
Labels: Feature, UI

#157 Feat: 스토리 작업 90% 완료.
  .vscode/settings.json
  api/story/index.ts
  components/avatar/avatar.module.scss
  components/family/diary/empty/family-diary-empty.tsx
  components/family/diary/family-diary-contents.tsx
  components/family/diary/family-diary.tsx
  components/family/growth/empty/family-growth-empty.tsx
  components/family/growth/family-growth-contents.tsx
  components/family/growth/family-growth.tsx
  components/family/growth/list/family-growth-list.tsx
  components/story/StoryItemSwiper.tsx
  components/story/detail/story-detail-add-comment.module.scss
  components/story/detail/story-detail-add-comment.tsx
  components/story/detail/story-detail-comments.module.scss
  components/story/detail/story-detail-comments.tsx
  components/story/detail/story-detail-header.module.scss
  components/story/detail/story-detail-header.tsx
  components/story/detail/story-detail-post.tsx
  components/story/item/story-item-header.module.scss
  components/story/item/story-item-header.tsx
  components/story/item/story-item-info.module.scss
  components/story/item/story-item-info.tsx
  components/story/item/story-item-swiper.module.scss
  components/story/item/story-item-swiper.tsx
  components/story/item/story-item.tsx
  components/story/list/story-list.module.scss
  components/story/list/story-list.tsx
  components/story/story.module.scss
  components/story/story.tsx
  hooks/queries/story/index.ts
  hooks/queries/story/mutation.ts
  hooks/use-intersect.ts
  package-lock.json
  package.json
  pages/story/[storyId]/index.tsx
  pages/story/index.tsx
  public/images/comment-icon.svg
  public/images/dummy-image.jpeg
  public/images/like-active-icon.svg
  public/images/like-icon.svg
  public/images/story/add-comment-icon.svg
  tsconfig.json
  types/story/details.ts
  types/story/index.ts
  utils/date/date.utils.ts
Labels: Feature, UI

#158 Feat: middleware 구현
  api/index.ts
  components/common/nav/nav-list/nav-list-item.module.scss
  hooks/usePullReload.tsx
  middleware.ts
  pages/index.module.scss
  pages/index.tsx
  pages/login/index.tsx
  pages/start-family/index.tsx
  utils/constants/middleware-data.ts
  utils/constants/nav-data.ts
Labels: Feature

#160 Fix: nav 로직 수정
  pages/_app.tsx
  utils/is-nav.ts
Labels: bug

#161 Feat: 다이어리 이미지 점 아이콘, 넘기기 기능 구현
  api/diaries/index.ts
  components/diaries/diary-content/comment/diary-comment-form.tsx
  components/diaries/diary-images/diary-images.module.scss
  components/diaries/diary-images/index.tsx
Labels: Feature, UI

#153 Feat: family page 스켈레톤 구현
  components/family/diary/family-diary.tsx
  components/family/growth/family-growth.module.scss
  components/family/growth/family-growth.tsx
  components/family/schedule/family-schedule.module.scss
  components/family/schedule/family-schedule.tsx
  components/growth/list/index.tsx
  components/growth/list/list-header/index.tsx
  components/growth/list/list-header/list-header.module.scss
  components/skeleton/family/calendar/calendar-skeleton.module.scss
  components/skeleton/family/calendar/index.tsx
  components/skeleton/family/diary/diary-skeleton.module.scss
  components/skeleton/family/diary/index.tsx
  components/skeleton/family/growth/growth-skeleton.module.scss
  components/skeleton/family/growth/index.tsx
  components/skeleton/family/test.tsx
  pages/growth/growth.module.scss
Labels: UI

#152 Feat: 성장기록 페이지 스켈레톤 ui 구현
  components/skeleton/growth/growth-detail/growth-detail.module.scss
  components/skeleton/growth/growth-detail/index.tsx
  components/skeleton/growth/growth-list/growth-list.module.scss
  components/skeleton/growth/growth-list/index.tsx
  components/skeleton/growth/test.tsx
  pages/growth/[growthId]/growth-detail.module.scss
  pages/growth/growth.module.scss
  pages/growth/index.tsx
  pages/test/skeleton/index.tsx
Labels: UI

#162 Feat: middleware 작업 완료
  api/my/groups/index.ts
  components/common/nav/nav-list/nav-list-item.tsx
  components/mypage/family/family-util-buttons/family-delete-button/delete-modal/delete-modal.tsx
  middleware.ts
  pages/mypage/family-management/index.module.scss
  pages/mypage/family-management/index.tsx
  utils/constants/middleware-data.ts
  utils/is-nav.ts
Labels: bug, Feature

#163 Fix: 카테고리 이미지 수정
  pages/growth/create/index.tsx
  public/images/category/abnormalSymptom-icon.png
  public/images/category/food-icon.png
  public/images/category/hospital-icon.png
  public/images/category/snack-icon.png
  utils/constants/growth.ts
Labels: bug

#167 Fix: 다이어리 이미지 업로드 오류 수정 등
  components/diaries/diary-content/content/index.tsx
  components/diaries/diary-content/diary-content.module.scss
  components/diaries/diary-content/diary-content.tsx
  components/diaries/diary-content/kebab/index.tsx
  components/diaries/diary-create/diary-create.tsx
  pages/calendar/calendar.module.scss
  pages/diaries/[diaryId]/index.tsx
Labels: bug, Feature

#170 Feat: 헤더가 페이지별로 다르게 나오도록 구현
  components/common/Header/Header.module.scss
  components/common/Header/back-header/index.tsx
  components/common/Header/create-header/index.tsx
  components/common/Header/index.tsx
  components/common/Header/main-header/index.tsx
  components/common/Header/warning-modal/index.tsx
  pages/_app.tsx
  public/images/header/logo.svg
  public/images/header/mypage-icon.svg
  public/images/header/search.svg
Labels: Feature, UI

#176 Fix: 페이지별 ui 수정
  components/calendar-monthly/calendar-todo-post-success.module.scss
  components/calendar-monthly/calendar-todo-profile.module.scss
  pages/calendar/[calendarId]/calendar-id.module.scss
  pages/calendar/create/create.module.scss
  pages/calendar/create/index.tsx
  pages/calendar/index.tsx
  pages/calendar/search/search.module.scss
  pages/diaries/[diaryId]/diary-id.module.scss
  pages/diaries/search/search.module.scss
  pages/growth/search/search.module.scss
Labels: bug, UI

#178 Fix: 마이페이지 이동 에러 수정
  components/calendar-monthly/calendar-todo-profile.module.scss
  components/common/Header/main-header/index.tsx
  components/growth/profile/profile.module.scss
  pages/growth/[growthId]/growth-detail.module.scss
Labels: bug

#179 Feat: memo component 분리 및 구현
  components/diaries/jihye/diary-edit-memo/diary-edit-memo.module.scss
  components/diaries/jihye/diary-edit-memo/index.tsx
  pages/growth/create/create.module.scss
  pages/growth/create/index.tsx
Labels: Feature, Refactoring

#182 Fix: 빌드 오류 해결
  components/diaries/diary-create/diary-create.tsx
  components/diaries/pet-checkbox.tsx
  components/family/diary/family-diary-contents-empty.tsx
  components/family/growth/family-growth-empty.tsx
  components/growth/category-inputs/category-inputs.module.scss
  components/growth/category-inputs/index.tsx
  components/growth/complete-modal/complete-modal.module.scss
  components/growth/complete-modal/index.tsx
  components/growth/list/list-header/index.tsx
  hooks/queries/growth/use-get-growth-queries.ts
  middleware.ts
  pages/_app.tsx
  pages/diaries/[diaryId]/index.tsx
  pages/growth/[growthId]/content/content.module.scss
  pages/growth/[growthId]/content/index.tsx
  pages/growth/[growthId]/edit/index.tsx
  pages/growth/[growthId]/index.tsx
  pages/growth/create/index.tsx
  pages/growth/index.tsx
  pages/test/button-test/index.module.scss
  pages/test/button-test/index.tsx
  pages/test/calendar/index.tsx
  pages/test/input-test/index.module.scss
  pages/test/input-test/index.tsx
  pages/test/kebab/index.tsx
  pages/test/modal-test/index.tsx
  pages/test/radio-test/index.tsx
  pages/test/refresh-test/index.tsx
  pages/test/skeleton/index.tsx
Labels: bug

#186 Fix: 일정 상세 시각, 검색 결과 등 수정
  components/calendar-monthly/calendar-todo.module.scss
  pages/calendar/[calendarId]/index.tsx
Labels: UI

#190 Fix: 오류 수정 및 브랜치 병합
  components/diaries/detail/add-comment/diary-detail-add-comment.module.scss
  components/mypage/pet/pet-list-item/pet-list-item.module.scss
  components/mypage/pet/pet-list-item/pet-list-item.tsx
  components/story/detail/add-comment/story-detail-add-comment.module.scss
Labels: bug
