Repository Donggrina/Frontend, pull requests merged in 2024-05, with the labels that each got.

#1 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#17 Update issue templates
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
Labels: documentation

#20 [#19] feat: 로그인 페이지 퍼블 및 버튼 공통 스타일 완료
  .eslintrc.js
  components/common/Button/Button.module.scss
  components/login/google-button/google-button.module.scss
  components/login/google-button/google-button.tsx
  components/login/kakao-button/kakao-button.module.scss
  components/login/kakao-button/kakao-button.tsx
  components/login/login-buttons/login-buttons.module.scss
  components/login/login-buttons/login-buttons.tsx
  components/login/login-top/login-top.module.scss
  components/login/login-top/login-top.tsx
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/login/index.module.scss
  pages/login/index.tsx
  public/images/login/google_logo.svg
  public/images/login/kakao_logo.svg
  public/images/login/logo.png
  small.ts
  styles/Home.module.css
  styles/globals.css
Labels: UI

#29 Refactor: 이미지 파일 확장자 변경 및 조건식 리펙토링
  components/common/Header/Header.module.scss
  components/common/Header/index.tsx
  pages/_app.tsx
  public/images/header/left-arrow.png
  public/images/header/left-arrow.svg
  public/images/header/sub-logo.jpg
  public/images/header/sub-logo.png
Labels: Refactoring

#25 Design: start-family 페이지 퍼블 완료
  components/start-family/introduce-text/introduce-text.module.scss
  components/start-family/introduce-text/introduce-text.tsx
  components/start-family/link-list/link-item.tsx
  components/start-family/link-list/link-list.module.scss
  components/start-family/link-list/link-list.tsx
  pages/start-family/index.module.scss
  pages/start-family/index.tsx
Labels: UI, Apply code review

#27 Feat: input 공통 컴포넌트 구현
  components/common/Input/Input.module.scss
  components/common/Input/index.tsx
  package-lock.json
  package.json
  pages/input-test/index.tsx
  styles/globals.css
  tsconfig.json
Labels: Feature, UI

#28 Feat: 헤더 컴포넌트 구현
  components/common/Header/Header.module.scss
  components/common/Header/index.tsx
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/images/header/left-arrow.png
  public/images/header/sub-logo.png
  styles/globals.css
  utils/IsHeader.ts
Labels: Feature, UI, question, Apply code review

#30 Chore: create main.yml
  .github/workflows/main.yml
Labels: documentation

#31 Chore: 모든 push 마다 npm i, lint, tsc, build 검사
  .github/workflows/test-every-push.yml
Labels: documentation

#32 fix: type error 수정
  components/common/Input/index.tsx
Labels: bug

#36 Fix: header 디자인 수정
  components/common/Header/Header.module.scss
  styles/globals.css
Labels: bug
